### PR TITLE
Use tick slabs to process audio playback into SDL's buffer

### PR DESCRIPTION
**Pull request by wallabra**
A "tick slab" is a slice of samples whose length corresponds to a 'tick' of the module.

This important refactor should significantly speed up playback by ensuring the entire player structure isn't updated for every single sample.

Do keep in mind this will make dealing with IT instrument envelopes a little bit trickier in the future ;)

WIP: investigate potential row/tick tempo issues, that may or may not exist, and if they do exist, may or may not have been induced by these changes.

### CODE REVIEW

**Comment by wallabra** [comment]
Should I remove the (here commented out) vestigial  `process` functions entirely? Y'know, the ones that computed a sample at a time.

They're made pointless after this refactor, and Rust appropriately warns that they're unused if left uncommented.  Even commented, they're wasting lines of code as it stands. The question is about whether it is useful to have the code around, even if commented, maybe as some sort of reference for the future? Or do you think this refactor obsoletes even that entirely?

**Comment by polyzium** [comment]
You can remove them, we have git commit history for a reason

**Comment by polyzium** [comment]
This whole thing is just broken. Some notes are being skipped, volume handling is broken, among other things. As for the speed improvements, sinc16 interpolation is just as slow as it was before

**Comment by wallabra** [comment]
I fixed playback, as well as a bunch of minor improvements now, including the sinc sampling's implementation.

**Comment by polyzium** [comment]
merged under a new branch

**Pull request merged**
